version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r aws-eb-webapp/requirements.txt
  build:
    commands:
      - python -m unittest discover -s aws-eb-webapp
artifacts:
  files:
    - '**/*'
  base-directory: aws-eb-webapp